### ISSUE TITLE
Unit system needs adjusting

### ISSUE THREAD

**Issue by CharlesMicou** [callumlawson/SpaceChips#1]
We need to sort out the unit system to move away from unity's arbitrary values and move towards a more sensible one (See OneNote Units page for further details), so that the physics engine starts making sense.

Also: start using the github wiki over OneNote?

**Comment by callumlawson** [comment]
Yay, space chips. Maybe I should veg less and get going!
I totally agree, I'll do some research. This is bound to be a solved
problem.
